### PR TITLE
fixed errors in readme and added restclient sample

### PR DESCRIPTION
**Pull request by Geertvdc**
# Description

While working through the samples i found some issues and fixed them.  Also added some extra sample next to CURL/postman using VSCode rest client plugin which is used a lot by devs.

Sample 1: 
- added .http file to easily test calls using  vs rest client

Sample 2:
- added dapr init --kubernetes in this readme instead of finding it in the linked doc
- added note for minikube for external ip's not being available

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] Code compiles correctly
* [X] Created/updated tests
* [X] Extended the documentation

### CODE REVIEW

**Comment by youngbupark** [comment]
> * I like how you were specific with the redis manifest naming (`redis-state.yaml` vs `redis.yaml`), given that redis can be used as a state store or as a pubsub component. If we rename it for this sample, I think we should rename it for the others as well. @youngbupark, @yaron2 do you agree with the more specific redis naming?

No, not now. I would keep redis.yaml.  We need to be careful to change the redis.yaml in the other standalone samples because CLI will create another redis.yaml unless it doesn't exist.

**Comment by ryanvolum** [comment]
> > * I like how you were specific with the redis manifest naming (`redis-state.yaml` vs `redis.yaml`), given that redis can be used as a state store or as a pubsub component. If we rename it for this sample, I think we should rename it for the others as well. @youngbupark, @yaron2 do you agree with the more specific redis naming?
> 
> No, not now. I would keep redis.yaml for now. We need to be careful to change the redis.yaml in the other standalone samples because CLI will create another redis.yaml unless it doesn't exist.

Good point. @Geertvdc, when dapr runs in standalone mode it currently creates a file called `redis.yaml` unless one already exists. Therefore we currently shouldn't rename the `redis.yaml` files. Could you undo those changes? We'd be interested in taking the rest of your contributions!

**Comment by Geertvdc** [comment]
OK I'll undo that later

**Comment by Geertvdc** [comment]
Reverted the changes to redis files as @ryanvolum requested.

**Pull request merged**
