### PR TITLE
Revert "Add 10.hello-docker-compose to build workflow"

### PR DESCRIPTION
**Pull request by youngbupark**
sample 10 doesn't have the image to be uploaded.

Reverts dapr/samples#263

### CODE REVIEW

**Comment by pruthvidhodda** [comment]
Should we remove building as well?

**Comment by youngbupark** [comment]
@pruthvidhodda @mukundansundar there is build target command. it is good to keep it as is to check if build is running correctly or not.

**Comment by mukundansundar** [comment]
build will try to run `docker-compose`

**Comment by youngbupark** [comment]
> build will try to run `docker-compose`

yes I know.

**Pull request merged**
