### PR TITLE
Cleanup for running 5. bindings locally

### PR DESCRIPTION
**Pull request by RicardoNiepel**
# Description

Adding the command for removing the local Kafka Docker Container

### CODE REVIEW

**Comment by yaron2** [comment]
cc @youngbupark @ryanvolum, any idea why the build is failing?

**Comment by youngbupark** [comment]
> cc @youngbupark @ryanvolum, any idea why the build is failing?

Interesting. I'm looking at it :(

**Comment by youngbupark** [comment]
@yaron2 @RicardoNiepel CI is fixed. it is good to merge.

**Comment by yaron2** [comment]
Thanks @youngbupark

**Pull request merged**
