### PR TITLE
Remove Lombok

### PR DESCRIPTION
**Pull request by brunoborges**
Lombok adds complexity to the build process and tooling support. It has become a bad practice adding Lombok to projects, and an impediment to the modernization of Java code to later versions of Java.

### CODE REVIEW

**Comment by brunoborges** [comment]
// @artursouza @DarqueWarrior

**Comment by artursouza** [comment]
@brunoborges Can you, please, provide some references on the statement that Lombok adds complexity? I have the opposite perception on this since the code is much cleaner. It can be more complex since you need to understand what Lombok is doing but that is true for any library that you bring in to a project.

**Comment by artursouza** [comment]
I am adding a flag to this PR until we decide a path forward for this. Thanks.

**Comment by brunoborges** [comment]
Lombok is not just a library. It injects itself into the compiler and uses internal APIs in the JDK that are not normally accessible, and on later versions of Java, are completely inaccessible. Lombok won't work on Java 17.

It also brings complexity as it requires IDEs to have Lombok-specific plugins to be able to understand the source code.

Best reference would be Lombok's source code and its GitHub issues regarding latest versions of Java.

**Comment by artursouza** [comment]
@brunoborges I am inclined to remove Lombok not because of perceived complexity (I see it offset by the simplification in the code), but because as a sample, I don't want other people to have to install more plug-ins to try this. I will keep the PR open to see if we get some community feedback on this.

@halspang @skyao Thoughts on this?

**Comment by halspang** [comment]
I agree with @artursouza. I don't mind Lombok and find that the removal of boilerplate is helpful. However, given that these are examples we want the barrier to entry to be as minimal as possible. Ideally, this code should just work and allow for new community members/adopters to come in and experiment without additional add-ons or tools required.

So in this case, yes, I am fine with removing Lombok from the examples.

**Comment by brunoborges** [comment]
Given that Dapr is a new project still in its early age, we could move this sample code to Java 16, and use Records.

**Comment by skyao** [comment]
I agreee with @brunoborges:

1. Lombok brings complexity which is not nessasorry to dapr. 
2.  I don't like Lombok because it changes the code: what you see is not what you get.

**Comment by artursouza** [comment]
@skyao Lombok is not used in Dapr, we used it in this example only. I can see how it might be too opinionated for an example. I personally don't see a problem with Lombok for apps - but it requires understanding what it does. Anyway, I am approving this PR.

**Review by artursouza — APPROVED** [review]

**Pull request merged**
